php.yml

diff --git a/.github/workflows/php.yml b/.github/workflows/php.yml
--- a/.github/workflows/php.yml
+++ b/.github/workflows/php.yml
@@ -11,11 +11,30 @@ permissions:
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
 
     steps:
     - uses: actions/checkout@v4
+
+    - name: Setup PHP
+      uses: shivammathur/setup-php@v2
+      with:
+        php-version: '8.2'
+        
+    - name: Install Composer
+      run: |
+        cd $GITHUB_WORKSPACE
+        curl -sS https://getcomposer.org/installer | php
+        sudo mv composer.phar /usr/local/bin/composer
+
+    - name: Check for composer.json
+      run: |
+        if [ -f "composer.json" ]; then
+          echo "composer.json found"
+        else
+          echo "ERROR: composer.json not found"
+          exit 1
+        fi
 
     - name: Validate composer.json and composer.lock
       run: composer validate --strict
@@ -33,7 +52,5 @@ jobs:
       run: composer install --prefer-dist --no-progress
 
     # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
-    # Docs: https://getcomposer.org/doc/articles/scripts.md
-
     # - name: Run test suite
     #   run: composer run-script test
